package seeds

import (
	repo "main/repository"
	"time"
)

var games = []repo.Game{
	{
		ID:              generateId("63bed80f04bedac5324c421a"),
		Title:           "Halo: The Master Chief Collection",
		Price:           39.99,
		Developer:       "Bungie",
		Publisher:       "Xbox Game Studio",
		Description:     "The Master Chief's iconic journey includes six games, built for PC and collected in a single integrated experience. Whether you're a long-time fan or meeting Spartan 117 for the first time, The Master Chief Collection is the definitive Halo gaming experience.",
		Score:           44,
		NumberOfScores:  9,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(2019, 12, 3, 0, 0, 0, 0, time.Local),
	},
	{
		ID:              generateId("63bed8174d991d50de422d6b"),
		Title:           "DOOM",
		Price:           19.99,
		Developer:       "id Software",
		Publisher:       "Bethesda Softworks",
		Description:     "Developed by id software, the studio that pioneered the first-person shooter genre and created multiplayer Deathmatch, DOOM returns as a brutally fun and challenging modern-day shooter experience. Relentless demons, impossibly destructive guns, and fast, fluid movement provide the foundation for intense, first-person combat - whether you're obliterating demon hordes through the depths of Hell in the single-player campaign, or competing against your friends in numerous multiplayer modes. Expand your gameplay experience using DOOM SnapMap game editor to easily create, play, and share your content with the world.",
		Score:           163,
		NumberOfScores:  37,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(216, 5, 13, 0, 0, 0, 0, time.Local),
	},
	{
		ID:              generateId("63bed81ec1bd88d167f66a8f"),
		Title:           "DOOM Eternal",
		Price:           39.99,
		Developer:       "id Software",
		Publisher:       "Bethesda Softworks",
		Description:     "Hell's armies have invaded Earth. Become the Slayer in an epic single-player campaign to conquer demons across dimensions and stop the final destruction of humanity. The only thing they fear... is you.",
		Score:           194,
		NumberOfScores:  44,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(2020, 3, 20, 0, 0, 0, 0, time.Local),
	},
	{
		ID:              generateId("63bed8230a995357e03daa9f"),
		Title:           "The Witcher® 3: Wild Hunt",
		Price:           29.99,
		Developer:       "CD PROJEKT RED",
		Publisher:       "CD PROJEKT RED",
		Description:     "You are Geralt of Rivia, mercenary monster slayer. Before you stands a war-torn, monster-infested continent you can explore at will. Your current contract? Tracking down Ciri — the Child of Prophecy, a living weapon that can alter the shape of the world.",
		Score:           209,
		NumberOfScores:  44,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(2015, 5, 18, 0, 0, 0, 0, time.Local),
	},
	{
		ID:              generateId("63bed828e88e68df55def4e4"),
		Title:           "God of War",
		Price:           49.99,
		Developer:       "Santa Monica Studio",
		Publisher:       "PlayStation PC LLC",
		Description:     "His vengeance against the Gods of Olympus years behind him, Kratos now lives as a man in the realm of Norse Gods and monsters. It is in this harsh, unforgiving world that he must fight to survive… and teach his son to do the same.",
		Score:           114,
		NumberOfScores:  24,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(2022, 1, 14, 0, 0, 0, 0, time.Local),
	},
	{
		ID:              generateId("63bed83259e1a173be264188"),
		Title:           "Cyberpunk 2077",
		Price:           59.99,
		Developer:       "CD PROJEKT RED",
		Publisher:       "CD PROJEKT RED",
		Description:     "Cyberpunk 2077 is an open-world, action-adventure RPG set in the dark future of Night City — a dangerous megalopolis obsessed with power, glamor, and ceaseless body modification.",
		Score:           172,
		NumberOfScores:  38,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(2019, 12, 3, 0, 0, 0, 0, time.Local),
	},
	{
		ID:              generateId("63bed8377f1a60b806b81cb8"),
		Title:           "ELDEN RING",
		Price:           59.99,
		Developer:       "FromSoftware Inc.",
		Publisher:       "Bandai Namco Entertainment",
		Description:     "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between",
		Score:           63,
		NumberOfScores:  15,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(2022, 2, 25, 0, 0, 0, 0, time.Local),
	},
	{
		ID:              generateId("63bed83dc0378d4abb338e72"),
		Title:           "Sekiro™: Shadows Die Twice - GOTY Edition",
		Price:           59.99,
		Developer:       "FromSoftware",
		Publisher:       "Activision, FromSoftware",
		Description:     "Game of the Year - The Game Awards 2019 Best Action Game of 2019 - IGN Carve your own clever path to vengeance in the award winning adventure from developer FromSoftware, creators of Bloodborne and the Dark Souls series. Take Revenge. Restore Your Honor. Kill Ingeniously.",
		Score:           46,
		NumberOfScores:  10,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(2019, 3, 21, 0, 0, 0, 0, time.Local),
	},
	{
		ID:              generateId("63bed843597757fc6bb4953e"),
		Title:           "Horizon Zero Dawn™ Complete Edition",
		Price:           49.99,
		Developer:       "Guerilla",
		Publisher:       "PlayStation PC LLC",
		Description:     "Experience Aloy's legendary quest to unravel the mysteries of a future Earth ruled by Machines. Use devastating tactical attacks against your prey and explore a majestic open world in this award-winning action RPG!",
		Score:           113,
		NumberOfScores:  24,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(2022, 8, 7, 0, 0, 0, 0, time.Local),
	},
	{
		ID:              generateId("63bed848240a8702cbdf09d4"),
		Title:           "Dead Space",
		Price:           59.99,
		Developer:       "Motive",
		Publisher:       "Electronic Arts",
		Description:     "The sci-fi survival-horror classic returns, completely rebuilt to offer an even more immersive experience — including visual, audio, and gameplay improvements — while staying faithful to the original game's thrilling vision.",
		Score:           74,
		NumberOfScores:  16,
		Screenshots:     []string{""},
		Discount:        0,
		DiscountExpDate: time.Now(),
		ReleaseDate:     time.Date(2023, 1, 27, 0, 0, 0, 0, time.Local),
	},
}
