package seeds

import (
	repo "main/repository"
	"time"
)

var users = []repo.User{
	{
		ID:           generateId("63bd69c3b2058767688d3d94"),
		Email:        "admin@test.com",
		Username:     "admin",
		Password:     generatePassword("test123"),
		Name:         "Stole Stojanovic",
		DateOfBirth:  "1900-01-01",
		IsAdmin:      true,
		PaymentCards: []repo.PaymentCard{},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6bd756fa7318db852016"),
		Email:        "jjeannet0@sakura.ne.jp",
		Username:     "jjeannet0",
		Password:     generatePassword("LciZEK3wB"),
		Name:         "Joelynn Jeannet",
		DateOfBirth:  "1987-04-15",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[0], paymentCards[3]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6d56d8eccac11b965956"),
		Email:        "kvell1@microsoft.com",
		Username:     "kvell1",
		Password:     generatePassword("3XS0qDBbh20s"),
		Name:         "Kellina Vell",
		DateOfBirth:  "1993-01-18",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[2]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6ce339dd5484c8d7b7a9"),
		Email:        "ascarlett2@yelp.com",
		Username:     "ascarlett2",
		Password:     generatePassword("LciZEK3wB"),
		Name:         "Ardra Scarlett",
		DateOfBirth:  "1976-11-10",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[3], paymentCards[4]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6d1bd0564a6e1c2de5b4"),
		Email:        "mheavy3@icio.us",
		Username:     "mheavy3",
		Password:     generatePassword("XrgYX3"),
		Name:         "Marabel Heavy",
		DateOfBirth:  "1997-10-07",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[4]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6d1fab372bf383a2dbc7"),
		Email:        "btregidgo4@latimes.com",
		Username:     "btregidgo4",
		Password:     generatePassword("X3y8AdkhX35A"),
		Name:         "Beck Tregidgo",
		DateOfBirth:  "1992-03-12",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[0], paymentCards[3], paymentCards[4]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6d235a1cbb4302d1f09a"),
		Email:        "gdunkerley5@wikipedia.org",
		Username:     "gdunkerley5",
		Password:     generatePassword("OwW99N3"),
		Name:         "Giffie Dunkerley",
		DateOfBirth:  "1970-09-29",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[0], paymentCards[3]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6d29bfdab9586c5bf162"),
		Email:        "lwoofendell6@multiply.com",
		Username:     "lwoofendell6",
		Password:     generatePassword("iKpKquj"),
		Name:         "Luelle Woofendell",
		DateOfBirth:  "1999-12-06",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[1], paymentCards[4]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6d40fb221e7af31f30dd"),
		Email:        "gcodlin7@eventbrite.com",
		Username:     "gcodlin7",
		Password:     generatePassword("DtJLZQ"),
		Name:         "Georgeanna Codlin",
		DateOfBirth:  "1993-11-12",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[2]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6ce339dd5484c8d7b7a9"),
		Email:        "sstrasse8@studiopress.com",
		Username:     "sstrasse8",
		Password:     generatePassword("jvmGdAh8B3G"),
		Name:         "Shani Strasse",
		DateOfBirth:  "1992-02-29",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[3], paymentCards[4]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
	{
		ID:           generateId("63bd6d3408644f39445e6ee0"),
		Email:        "kvan9@cornell.edu",
		Username:     "kvan9",
		Password:     generatePassword("FHkpNdlo"),
		Name:         "Kalila Van Velden",
		DateOfBirth:  "1979-01-24",
		IsAdmin:      false,
		PaymentCards: []repo.PaymentCard{paymentCards[0]},
		CreatedAt:    time.Now(),
		UpdatedAt:    time.Now(),
	},
}

var paymentCards = []repo.PaymentCard{
	{
		CardNumber: "4226822151457279",
		ExpDate:    "3/2029",
		Cvc:        712,
	},
	{
		CardNumber: "4556364176301422",
		ExpDate:    "6/2027",
		Cvc:        287,
	},
	{
		CardNumber: "4024007159366797",
		ExpDate:    "9/2031",
		Cvc:        786,
	},
	{
		CardNumber: "5366992859954740",
		ExpDate:    "12/2024",
		Cvc:        899,
	},
	{
		CardNumber: "348136569715066",
		ExpDate:    "2/2026",
		Cvc:        313,
	},
}
