#database config
  connectionString: mongodb+srv://db_user:2ogDOpti8r2jAePZ@steam-clone-db.hbsaqon.mongodb.net/?retryWrites=true&w=majority
  name: steam-clone-db
  username: db_user
  password: 2ogDOpti8r2jAePZ
